export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_PURCHASE = 'INIT_PURCHASE';
export const PURCHASE_BURGER = 'PURCHASE_BURGER';
export const PURCHASE_BURGER_SUCESS = 'PURCHASE_BURGER_SUCESS';
export const PUCHASE_BURGER_FAIL = 'PUCHASE_BURGER_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNIN_START = 'SIGNIN_START';

export const AUTH_SUCESS = 'AUTH_SUCESS';
export const AUTH_FAIL = 'AUTH_FAIL';